### ISSUE TITLE
Where are the models or how to train or get these models? model_path=$WS/models/sft-data.wmt20-train+llm.nllb-200-1.3B/checkpoint-5209

### ISSUE THREAD

**Issue by wangpichao** [zwhe99/FeedbackMT#1]

**Comment by zwhe99** [comment]
Here is the training script: 
https://github.com/zwhe99/FeedbackMT/blob/main/train_scripts/sft-data.wmt20-train%2Bllm.nllb-200-1.3B.sh

You can find all the training scripts for this paper in this folder.

**Comment by wangpichao** [comment]
Thanks for reply, and problem solved.
