### ISSUE TITLE
Could you help me check your unbabel-comet and huggingface-hub version?

### ISSUE THREAD

**Issue by wangpichao** [zwhe99/FeedbackMT#2]

**Comment by zwhe99** [comment]
I used `unbabel-comet==2.2.0`. It has a known [issue](https://github.com/Unbabel/COMET/issues/186), and I am not sure if the newer version has fixed this.

You can fix this by running `sed -i 's/pred.scores/pred["scores"]/g' /YOUR_PATH/site-packages/comet/models/base.py`.

`transformers==4.28.1`
`huggingface-hub==0.16.4`

**Comment by wangpichao** [comment]
Thank you. The reason why I ask you is that for the raft+ training, it always reports errors, and i think the problems are the version conflict between unbable-comet, trl and hugingface. I will try what you mentioned versions and methods.

**Comment by zwhe99** [comment]
Sorry for the inconvenience. If there is anything I can help, feel free to contact me.
